"$schema" = "./kaledis.schema.json"

experimental_hmr = false

[project]
name = "test"
love_path = "C:/Program Files/LOVE"
src_path="src"
detect_modules=true

[window]
title = "Untitled"

[audio]

[polyfill]
location = "../../"